
import DAO.EquipamentosDAO;
import DTO.EquipamentosDTO;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author User
 */
public class TelaProdutos extends javax.swing.JFrame {

    /**
     * Creates new form TelaProdutos
     */
    public TelaProdutos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtdados = new javax.swing.JTextField();
        txtpotencia = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtmarca = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaprodutos = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        txtid = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jPanel1);
        jPanel1.setBounds(60, 600, 40, 40);

        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(10, 590, 40, 50);

        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(20, 200, 210, 40);

        jButton4.setContentAreaFilled(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(20, 140, 210, 40);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jLabel4.setText("Potência:");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(50, 160, 70, 19);

        jLabel2.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        jLabel2.setText("Inserir produtos");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(120, 30, 220, 32);

        jLabel3.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jLabel3.setText("Dados da usina:");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(10, 120, 120, 20);

        txtdados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdadosActionPerformed(evt);
            }
        });
        jPanel3.add(txtdados);
        txtdados.setBounds(120, 120, 200, 22);
        jPanel3.add(txtpotencia);
        txtpotencia.setBounds(120, 160, 200, 22);

        jLabel5.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jLabel5.setText("Marca:");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(70, 200, 60, 40);
        jPanel3.add(txtmarca);
        txtmarca.setBounds(120, 210, 200, 22);

        jButton5.setText("Salvar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton5);
        jButton5.setBounds(170, 240, 70, 22);

        jLabel6.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        jLabel6.setText("Lista de produtos cadastrados");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(410, 30, 370, 30);

        tabelaprodutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Dados", "Potência", "Marca"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaprodutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaprodutosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaprodutos);

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(380, 70, 330, 150);

        jButton6.setText("Atualizar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton6);
        jButton6.setBounds(520, 230, 90, 22);

        jButton7.setText("Limpar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton7);
        jButton7.setBounds(250, 240, 70, 22);

        jButton8.setText("Excluir");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton8);
        jButton8.setBounds(620, 230, 90, 22);

        txtid.setEditable(false);
        txtid.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.add(txtid);
        txtid.setBounds(120, 80, 200, 22);

        jLabel7.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jLabel7.setText("ID:");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(100, 80, 20, 19);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(360, 160, 720, 390);

        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(20, 300, 210, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\Frame 14.png")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1200, 650);

        setSize(new java.awt.Dimension(1220, 693));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        dispose();
        TelaInicial ti1 = new TelaInicial();
        ti1.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
             dispose();
        TelaClientes tc1 = new TelaClientes();
        tc1.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int teste = JOptionPane.showConfirmDialog(null, "Deseja mesmo deslogar da conta?");
        if (teste == 0) {
        dispose();
        Principal l1 = new Principal();
        l1.setVisible(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            String dados;
            String potencia;
            String marca;

            marca = txtmarca.getText();
            dados = txtdados.getText();
            potencia = txtpotencia.getText();
            EquipamentosDTO objEquipamentosDTO = new EquipamentosDTO();
            objEquipamentosDTO.setDados(dados);
            objEquipamentosDTO.setPotencia(potencia);
            objEquipamentosDTO.setMarca(marca);
            
            EquipamentosDAO objequipamentosdao = new EquipamentosDAO();
            objequipamentosdao.cadastrarEquipamento(objEquipamentosDTO);
            JOptionPane.showMessageDialog(null, "Equipamento cadastrado no banco de dados");
            listarProdutos();
             } catch (Exception e) {
                 
                 
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        listarProdutos();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        limparCampos();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void tabelaprodutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaprodutosMouseClicked
        CarregarCampos();
    }//GEN-LAST:event_tabelaprodutosMouseClicked

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
          try {
             ExcluirProduto();
             JOptionPane.showMessageDialog(null, "Produto excluído com sucesso");
             listarProdutos();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Selecione um produto para excluir");
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void txtdadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdadosActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
        TelaAgendamento tcp = new TelaAgendamento();
        tcp.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaProdutos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaprodutos;
    private javax.swing.JTextField txtdados;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtmarca;
    private javax.swing.JTextField txtpotencia;
    // End of variables declaration//GEN-END:variables
    private void listarProdutos() {
        try {
            EquipamentosDAO objEquipamentosDAO = new EquipamentosDAO();
            DefaultTableModel model = (DefaultTableModel) tabelaprodutos.getModel();
            model.setNumRows(0);
            ArrayList<EquipamentosDTO> lista = objEquipamentosDAO.PesquisarEquipamentos();
            
            for (int i = 0; i < lista.size(); i++) {
                model.addRow(new Object[] {
                lista.get(i).getId(),
                lista.get(i).getDados(),
                lista.get(i).getPotencia(),
                lista.get(i).getMarca()              
             });
            }
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "listar valores" + erro);

        }
    }
    
      private void CarregarCampos() {
          int setar = tabelaprodutos.getSelectedRow();
          txtid.setText(tabelaprodutos.getModel().getValueAt(setar, 0).toString());
          txtdados.setText(tabelaprodutos.getModel().getValueAt(setar, 1).toString());
          txtpotencia.setText(tabelaprodutos.getModel().getValueAt(setar, 2).toString());
          txtmarca.setText(tabelaprodutos.getModel().getValueAt(setar, 3).toString());

      }
    
          private void limparCampos() {
          txtid.setText("");
          txtmarca.setText("");
          txtpotencia.setText("");
          txtdados.setText("");
          
      }
          
        private void ExcluirProduto() {
        int id = 0;
        id = Integer.parseInt(txtid.getText());
        
        EquipamentosDTO objEquipamentosDTO = new EquipamentosDTO();
        objEquipamentosDTO.setId(id);
        EquipamentosDAO objEquipamentosDAO = new EquipamentosDAO();
       objEquipamentosDAO.ExcluirProduto(objEquipamentosDTO);
      }
    
}