
import DAO.UsuarioDAO;
import DTO.UsuarioDTO;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author User
 */
public class TelaUsuariosAdm extends javax.swing.JFrame {

    /**
     * Creates new form TelaUsuariosAdm
     */
    public TelaUsuariosAdm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txtemail = new javax.swing.JTextField();
        txtsenha = new javax.swing.JTextField();
        txttelefone = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtnome = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelafuncionario = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        btnsalvar = new javax.swing.JButton();
        txtid = new javax.swing.JTextField();
        btnlistar = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusable(false);
        setResizable(false);
        getContentPane().setLayout(null);

        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(20, 600, 30, 40);

        jButton2.setBorder(null);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(30, 150, 200, 30);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);
        jPanel2.add(txtemail);
        txtemail.setBounds(70, 90, 200, 22);

        txtsenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsenhaActionPerformed(evt);
            }
        });
        jPanel2.add(txtsenha);
        txtsenha.setBounds(70, 120, 200, 22);
        jPanel2.add(txttelefone);
        txttelefone.setBounds(70, 150, 200, 22);

        jLabel2.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        jLabel2.setText("Criar funcionário");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(70, 0, 204, 32);
        jPanel2.add(txtnome);
        txtnome.setBounds(70, 60, 200, 22);

        jLabel5.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jLabel5.setText("Senha:*");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(10, 120, 51, 19);

        jLabel3.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jLabel3.setText("Nome:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(10, 60, 56, 19);

        jLabel4.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jLabel4.setText("Email:*");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(10, 90, 56, 19);

        jLabel6.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jLabel6.setText("Telefone:");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(0, 150, 62, 19);

        jLabel7.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        jLabel7.setText("Lista de funcionários cadastrados");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(360, 0, 299, 32);

        tabelafuncionario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Nome", "Email", "Senha", "Telefone"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelafuncionario.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                tabelafuncionarioMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                tabelafuncionarioMouseMoved(evt);
            }
        });
        tabelafuncionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelafuncionarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelafuncionario);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(300, 30, 410, 140);

        jLabel8.setText("ID:");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(30, 30, 37, 30);

        btnsalvar.setText("Salvar");
        btnsalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalvarActionPerformed(evt);
            }
        });
        jPanel2.add(btnsalvar);
        btnsalvar.setBounds(120, 180, 70, 22);

        txtid.setEditable(false);
        txtid.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.add(txtid);
        txtid.setBounds(70, 30, 200, 22);

        btnlistar.setText("Atualizar");
        btnlistar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnlistar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlistarActionPerformed(evt);
            }
        });
        jPanel2.add(btnlistar);
        btnlistar.setBounds(530, 180, 80, 22);

        jButton3.setText("Excluir");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);
        jButton3.setBounds(620, 180, 80, 22);

        jButton4.setText("Limpar");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4);
        jButton4.setBounds(200, 180, 70, 22);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(360, 150, 700, 210);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(60, 600, 40, 40);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(360, 440, 400, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\Frame 16.png")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1200, 664);

        setSize(new java.awt.Dimension(1202, 691));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int teste = JOptionPane.showConfirmDialog(null, "Deseja mesmo deslogar da conta?");
        if (teste == 0) {
            dispose();
            Principal l1 = new Principal();
            l1.setVisible(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
        TelaInicialAdm tiadm1 = new TelaInicialAdm();
        tiadm1.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtsenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsenhaActionPerformed

    private void btnsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalvarActionPerformed
        try {
            String nome, email, senha, telefone;
            nome = txtnome.getText();
            email = txtemail.getText();
            senha = txtsenha.getText();
            telefone = txttelefone.getText();
            UsuarioDTO objUsuarioDTO = new UsuarioDTO();
            objUsuarioDTO.setNome_usuario(nome);
            objUsuarioDTO.setEmail_usuario(email);
            objUsuarioDTO.setSenha_usuario(senha);
            objUsuarioDTO.setTelefone_usuario(telefone);

            UsuarioDAO objusuariodao = new UsuarioDAO();
            objusuariodao.cadastrarusuario(objUsuarioDTO);
            JOptionPane.showMessageDialog(null, "Funcionário cadastrado no banco de dados");
            listarValores();
        } catch (Exception erro) {

        }


    }//GEN-LAST:event_btnsalvarActionPerformed

    private void btnlistarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlistarActionPerformed
        listarValores();
    }//GEN-LAST:event_btnlistarActionPerformed

    private void tabelafuncionarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelafuncionarioMouseClicked
           try {
            CarregarCampos();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Primeiro atualize a tabela");
        }

    }//GEN-LAST:event_tabelafuncionarioMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        limparCampos();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
             ExcluirFuncionario();
             JOptionPane.showMessageDialog(null, "Funcionário excluído com sucesso");
             listarValores();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Selecione um funcionário para excluir");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tabelafuncionarioMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelafuncionarioMouseDragged
        
    }//GEN-LAST:event_tabelafuncionarioMouseDragged

    private void tabelafuncionarioMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelafuncionarioMouseMoved
      
    }//GEN-LAST:event_tabelafuncionarioMouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaUsuariosAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaUsuariosAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaUsuariosAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaUsuariosAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaUsuariosAdm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnlistar;
    private javax.swing.JButton btnsalvar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelafuncionario;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtnome;
    private javax.swing.JTextField txtsenha;
    private javax.swing.JTextField txttelefone;
    // End of variables declaration//GEN-END:variables
    private void listarValores() {
        try {
            UsuarioDAO objUsuarioDAO = new UsuarioDAO();
            DefaultTableModel model = (DefaultTableModel) tabelafuncionario.getModel();
            model.setNumRows(0);
            ArrayList<UsuarioDTO> lista = objUsuarioDAO.PesquisarUsuario();

            for (int i = 0; i < lista.size(); i++) {
                model.addRow(new Object[]{
                    lista.get(i).getId_usuario(),
                    lista.get(i).getNome_usuario(),
                    lista.get(i).getEmail_usuario(),
                    lista.get(i).getSenha_usuario(),
                    lista.get(i).getTelefone_usuario()
                });
            }
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "listar valores" + erro);

        }
    }
          private void CarregarCampos() {
          int setar = tabelafuncionario.getSelectedRow();
          
          txtid.setText(tabelafuncionario.getModel().getValueAt(setar, 0).toString());
          txtnome.setText(tabelafuncionario.getModel().getValueAt(setar, 1).toString());
          txtemail.setText(tabelafuncionario.getModel().getValueAt(setar, 2).toString());
          txtsenha.setText(tabelafuncionario.getModel().getValueAt(setar, 3).toString());
          txttelefone.setText(tabelafuncionario.getModel().getValueAt(setar, 4).toString());
      }
      private void limparCampos() {
          txtid.setText("");
          txtnome.setText("");
          txtemail.setText("");
          txtsenha.setText("");
          txttelefone.setText("");
      }
      private void ExcluirFuncionario() {
          int id_funcionario;
          id_funcionario = Integer.parseInt(txtid.getText());
          UsuarioDTO objUsuarioDTO = new UsuarioDTO();
          objUsuarioDTO.setId_usuario(id_funcionario);
          UsuarioDAO objUsuarioDAO = new UsuarioDAO();
          objUsuarioDAO.ExcluirUsuario(objUsuarioDTO);
      }
}
